apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: kube-prometheus-stack
spec:
  dnsNames:
    - "grafana.kubernetes.giuseppebosa.eu"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
  secretName: grafana-certificate
