---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-auth
  namespace: kube-prometheus-stack
spec:
  basicAuth:
    secret: prometheus-auth-secret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingressroute
  namespace: kube-prometheus-stack
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.kubernetes.giuseppebosa.eu`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-prometheus
          port: 9090
      middlewares:
      - name: prometheus-auth

  tls:
    secretName: prometheus-certificate
