---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-ingressroute
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`harbor.kubernetes.giuseppebosa.eu`)
      kind: Rule
      services:
        - name: harbor-portal
          port: 80
    - match: Host(`registry.kubernetes.giuseppebosa.eu`)
      kind: Rule
      services:
        - name: harbor-registry
          port: 5000
  tls:
    secretName: harbor-certificate
