---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-ingressroute
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`harbor.kubernetes.giuseppebosa.eu`)
      kind: Rule
      services:
        - name: harbor-portal
          port: 80
    - match: |
        Host(`harbor.kubernetes.giuseppebosa.eu`) && (PathPrefix(`/api/`) || PathPrefix(`/service/`) || PathPrefix(`/v2/`) || PathPrefix(`/chartrepo/`) || PathPrefix(`/c/`))
      kind: Rule
      services:
        - name: harbor-core
          port: 80

  tls:
    secretName: harbor-certificate
