apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-ingressroute
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.kubernetes.giuseppebosa.eu`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
  tls:
    secretName: portainer-certificate
